version: '3'
services:
  devops:
    image: bhaskarone/java:latest
    ports:
      - "87:80"
    deploy:
      replicas: 3

  aws:
    image:  bhaskarone/azure:latest
    ports:
      - "88:80"
    deploy:
      replicas: 3

  datascience:
    image:  bhaskarone/aws:latest
    ports:
      - "89:80"
    deploy:
      replicas: 3
